### ISSUE TITLE
Make `charm_tracing_config` compatible with cos-agent

### ISSUE THREAD

**Issue by mmkay** [canonical/tempo-k8s-operator#154] opened 2024-07-29 11:04 UTC
### Enhancement Proposal

Our current implementation of `charm_tracing_config` [in tracing lib](https://github.com/canonical/tempo-k8s-operator/blob/main/lib/charms/tempo_k8s/v2/tracing.py#L926) uses `TracingEndpointRequirer` as the passed type. However, `COSAgentProvider` is going to have the same methods once canonical/grafana-agent-operator#144 is merged. As charm libraries cannot (shouldn't?) depend on each other, we might need to provide a way to pass the method along the full Requirer object.

**Comment by PietroPasotti** [comment] 2024-07-29 11:11
The intention of `charm_tracing_config` was that each library implementing a tracing interface should provide its own to avoid adding precisely this kind of serendipitous dependency

I'm inclined to say: cos-agent is a different interface (that provides tracing, among other things), so it should be exposing its own `charm_tracing_config` method.

If your charm is using tracing directly, you will use `charms.tempo_k8s.v2.tracing.charm_tracing_config`, if you're using cos-agent, you will use `charms.something.v1.cos_agent.charm_tracing_config`.

This avoids situations where an update to the tracing lib breaks a charm using cos-agent

**Comment by PietroPasotti** [comment] 2024-07-29 11:12
so, not a bug, but a feature :P

**Comment by PietroPasotti** [comment] 2024-08-15 12:32
this has been fixed by https://github.com/canonical/grafana-agent-operator/pull/144

**Closed by PietroPasotti** 2024-08-15 12:32 UTC
Labels: Status: Triage, Type: Enhancement
